[package]
name = "life"
version = "0.1.0"
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
rustc-hash = "2.1"

[lib]
crate-type = ["cdylib"]
path = "life.rs"

[profile.release]
lto = true

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = false
