[package]
name = "life"
version = "0.1.0"
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
ahash = { version = "0.8", default-features = false, features = ["compile-time-rng"] }

[lib]
crate-type = ["cdylib"]
path = "life.rs"

[profile.release]
lto = true
strip = true
